<a href="https://colab.research.google.com/github/Ashima010302/PCS221/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random

rows = 20000
cols = 10000

filename = "large_matrix.txt"

with open(filename, "w") as f:
    for i in range(rows):
        row = [str(random.randint(0, 100)) for j in range(cols)]
        f.write(" ".join(row) + "\n")

print("File created successfully!")


File created successfully!


In [ ]:
import numpy as np

matrix_data = []
with open('large_matrix.txt', 'r') as f:
    for line in f:
        row = [int(x) for x in line.strip().split()]
        matrix_data.append(row)

matrix = np.array(matrix_data)

print(f"Matrix loaded with shape: {matrix.shape}")
print("First 3 rows of the matrix:")
print(matrix[:3, :5]) # Print first 3 rows and first 5 columns for brevity

Matrix loaded with shape: (20000, 10000)
First 3 rows of the matrix:
[[34 26 14 57 40]
 [85 90 77 20 83]
 [39 41 75 47 57]]


In [ ]:
first_row = matrix[0, :]


for i in range(1, matrix.shape[0]):
    matrix[i, :] = first_row

print("Matrix after assigning subsequent rows based on the first row:")
print("First 5 rows and first 5 columns of the modified matrix:")
print(matrix[:5, :5])


Matrix after assigning subsequent rows based on the first row:
First 5 rows and first 5 columns of the modified matrix:
[[34 26 14 57 40]
 [34 26 14 57 40]
 [34 26 14 57 40]
 [34 26 14 57 40]
 [34 26 14 57 40]]


In [ ]:
unique_elements, counts = np.unique(matrix, return_counts=True)
element_counts = dict(zip(unique_elements, counts))

print("Unique elements and their counts:")
# Print only a subset if there are too many unique elements
if len(element_counts) > 20:
    print(dict(list(element_counts.items())[:10])) # Print first 10 for brevity
    print("...")
    print(dict(list(element_counts.items())[-10:])) # Print last 10 for brevity
else:
    print(element_counts)

print(f"\nTotal unique elements: {len(unique_elements)}")

Unique elements and their counts:
{np.int64(0): np.int64(1940000), np.int64(1): np.int64(1760000), np.int64(2): np.int64(1820000), np.int64(3): np.int64(2000000), np.int64(4): np.int64(1860000), np.int64(5): np.int64(2140000), np.int64(6): np.int64(1980000), np.int64(7): np.int64(2180000), np.int64(8): np.int64(2000000), np.int64(9): np.int64(2140000)}
...
{np.int64(91): np.int64(1760000), np.int64(92): np.int64(2080000), np.int64(93): np.int64(1700000), np.int64(94): np.int64(1900000), np.int64(95): np.int64(1920000), np.int64(96): np.int64(2360000), np.int64(97): np.int64(2220000), np.int64(98): np.int64(2040000), np.int64(99): np.int64(2120000), np.int64(100): np.int64(1960000)}

Total unique elements: 101


In [ ]:
num_bins = 10
bins = np.linspace(0, 101, num_bins + 1) # Define 10 bins for values 0-100, 101 to include 100 in the last bin

# Create grouped_matrix by assigning each element to its bin index
grouped_matrix = np.digitize(matrix, bins) - 1 # np.digitize returns bin index starting from 1, subtract 1 to make it 0-indexed

print(f"Defined {num_bins} bins:")
for i in range(num_bins):
    lower = int(bins[i])
    upper = int(bins[i+1]-1) # Adjust upper bound for display
    print(f"Bin {i}: [{lower}-{upper}]")

print("\nFirst 5 rows and 5 columns of the grouped_matrix:")
print(grouped_matrix[:5, :5])

unique_bin_ids, bin_counts = np.unique(grouped_matrix, return_counts=True)
print("\nUnique bin identifiers and their counts in grouped_matrix:")
print(dict(zip(unique_bin_ids, bin_counts)))


Defined 10 bins:
Bin 0: [0-9]
Bin 1: [10-19]
Bin 2: [20-29]
Bin 3: [30-39]
Bin 4: [40-49]
Bin 5: [50-59]
Bin 6: [60-69]
Bin 7: [70-79]
Bin 8: [80-89]
Bin 9: [90-100]

First 5 rows and 5 columns of the grouped_matrix:
[[3 2 1 5 3]
 [3 2 1 5 3]
 [3 2 1 5 3]
 [3 2 1 5 3]
 [3 2 1 5 3]]

Unique bin identifiers and their counts in grouped_matrix:
{np.int64(0): np.int64(21840000), np.int64(1): np.int64(20680000), np.int64(2): np.int64(19420000), np.int64(3): np.int64(19840000), np.int64(4): np.int64(19160000), np.int64(5): np.int64(19760000), np.int64(6): np.int64(19080000), np.int64(7): np.int64(20340000), np.int64(8): np.int64(19820000), np.int64(9): np.int64(20060000)}


In [ ]:
rows, cols = matrix.shape
matrix_B = np.random.randint(0, 101, size=(rows, cols))

# matrix addition
matrix_sum = matrix + matrix_B

# matrix subtraction
matrix_difference = matrix - matrix_B

print(f"Shape of matrix_sum: {matrix_sum.shape}")
print(f"Shape of matrix_difference: {matrix_difference.shape}")

print("\nFirst 5 rows and 5 columns of matrix_sum:")
print(matrix_sum[:5, :5])

print("\nFirst 5 rows and 5 columns of matrix_difference:")
print(matrix_difference[:5, :5])

Shape of matrix_sum: (20000, 10000)
Shape of matrix_difference: (20000, 10000)

First 5 rows and 5 columns of matrix_sum:
[[130  46  92 122  67]
 [113  69  22 152 125]
 [ 97  72  89  58  51]
 [119  28  85  92 129]
 [ 56 103 103  99 108]]

First 5 rows and 5 columns of matrix_difference:
[[-62   6 -64  -8  13]
 [-45 -17   6 -38 -45]
 [-29 -20 -61  56  29]
 [-51  24 -57  22 -49]
 [ 12 -51 -75  15 -28]]


In [ ]:
N = 100
square_matrix = np.zeros((N, N), dtype=int)

for r in range(N):
    for c in range(N):
        square_matrix[r, c] = (r + c) % 2

print(f"Shape of the square_matrix: {square_matrix.shape}")
print("First 5x5 sub-section of the square_matrix:")
print(square_matrix[:5, :5])

Shape of the square_matrix: (100, 100)
First 5x5 sub-section of the square_matrix:
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [ ]:
tuple_matrix = [
    [ (1, 2), (3, 4), (5, 6) ],
    [ (7, 8), (9, 10), (11, 12) ],
    [ (13, 14), (15, 16), (17, 18) ]
]

resultant_matrix = []

for row in tuple_matrix:
    resultant_row = []
    for tup in row:
        resultant_row.append(sum(tup))
    resultant_matrix.append(resultant_row)

print("Original Tuple Matrix:")
for row in tuple_matrix:
    print(row)

print("\nResultant Matrix (row-wise element addition):")
for row in resultant_matrix:
    print(row)

Original Tuple Matrix:
[(1, 2), (3, 4), (5, 6)]
[(7, 8), (9, 10), (11, 12)]
[(13, 14), (15, 16), (17, 18)]

Resultant Matrix (row-wise element addition):
[3, 7, 11]
[15, 19, 23]
[27, 31, 35]
